### ISSUE TITLE
gulp init not working

### ISSUE THREAD

**Issue by cfnz** [lgdd/liferay-startbootstrap#1]
Hi,

Just trying to get started with Liferay themeing/bootstrap or head down the wordpress track... (yes, quite different options)...

Just following instructions:

- Clone or download this repository
- Go to one theme's root folder
- Run npm install
- Run gulp init and follow instructions
- Run gulp deploy

And I get the following error... not that experienced at this, so not sure where to start.

Any help appreciated... running on Ubuntu 18.04 and using nvm.
```
gulp init
fs.js:25
'use strict';
^

ReferenceError: internalBinding is not defined
    at fs.js:25:1
    at req_ (/home/colin/Desktop/Temp/test-liferay-themes-bootstrap/liferay-startbootstrap/startbootstrap-freelancer-theme/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/home/colin/Desktop/Temp/test-liferay-themes-bootstrap/liferay-startbootstrap/startbootstrap-freelancer-theme/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/home/colin/Desktop/Temp/test-liferay-themes-bootstrap/liferay-startbootstrap/startbootstrap-freelancer-theme/node_modules/graceful-fs/fs.js:1:99)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
```

**Comment by lgdd** [comment]
Thanks for reporting. I'm on it.

**Comment by lgdd** [comment]
Dependencies to **liferay-theme-deps-7.1** and **liferay-theme-tasks** has been updated to latest version.

@cfnz Let me know this fix the issue for you.

**Comment by cfnz** [comment]
Yes indeed, thanks very much! Now I just have to figure out how it works and if I can import other themes... this will be a great help!
